spring:
    application:
        name: ace-monitor
    cloud:
        consul:
            enabled: true
            host: 127.0.0.1
            port: 8500
            discovery:
              healthCheckPath: /actuator/health
              healthCheckInterval: 5s
              instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
              register: true
              enabled: true

server:
    port: 8764 #启动端口

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


