spring:
  profiles:
    active: core, db
  message:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  DEBUG